from dataclasses import dataclass, field
from typing import NamedTuple

import numpy as np

from sting.utils.dynamical_systems import DynamicalVariables, StateSpaceModel


class InitialConditionsEMT(NamedTuple):
    x_t1: float
    x_t2: float
    t_m: float


@dataclass(slots=True)
class SteamTurbine2A:
    """
    A 2nd order simplified model of a steam turbine assuming that 
    the crossover time constant is negligible compared to the reheater
    time constant (Kundur, page 427).
    
               ┌───────────────────────────────────────────────┐
    Δu_vlv ───▶│ (1 + s*f_hp*tau_rh) / (1+s*tau_ch)(1+s*tau_rh)│───▶ Δt_m
               └───────────────────────────────────────────────┘

    where the inputs and states are defined as follows:
        - Δu_vlv: Change in the control valve.
        - Δt_m: Change in turbine torque.
    and the parameters are defined as follows
        - f_hp: Fraction of turbine power generated by the high
            pressure section.
        - tau_rh: Time constant of the reheater, in seconds.
        - tau_ch: Time constant of the main inlet volumes and steam
            chest, in seconds.
    """
    tau_rh_s: float
    tau_ch_s: float
    f_hp_pu: float

    A: np.ndarray = None   
    B: np.ndarray = None
    C: np.ndarray = None

    emt_init: InitialConditionsEMT = field(init=False)

    def __post_init__(self):
        # Compute state-space realization
        a0 = 1 / (self.tau_ch_s*self.tau_rh_s)
        a1 = (self.tau_ch_s+self.tau_rh_s) / (self.tau_ch_s*self.tau_rh_s)
        b0 = 1
        b1 = self.f_hp_pu*self.tau_rh_s
        self.A = np.array([
            [  0,  1], 
            [-a0,-a1]
        ])
        self.B = np.array([[0],[1]])
        self.C = np.array([[b0, b1]])

    def get_steady_state(self, u_vlv:float, t_m:float=None) -> InitialConditionsEMT:
        u0 = np.array([u_vlv])
        x0 = np.linalg.solve(self.A, -self.B@u0)

        self.emt_init = InitialConditionsEMT(*x0, t_m=t_m)
        return self.emt_init

    def get_small_signal_model(self, x_t1:float, x_t2:float, u_vlv:float):
        ssm = StateSpaceModel(
            A=self.A,
            B=self.B,
            C=self.C,
            D=np.array([[0]]),
            x=DynamicalVariables(name=['x_t1', 'x_t2'], init=[x_t1, x_t2]),
            u=DynamicalVariables(name=['u_vlv'], init=[u_vlv]),
        )
        return ssm

    def get_quadratic_bilinear_model(self, x_t1:float, x_t2:float, u_vlv:float):
        ssm = self.get_small_signal_model(x_t1, x_t2, u_vlv)
        return ssm.to_quadratic_bilinear()

    def get_derivatives_step_emt(self, x_t1:float, x_t2:float, u_vlv:float) -> float:
        x = np.array([x_t1, x_t2])
        dx = self.A@x + self.B@np.array([u_vlv])
        return list(dx)

    def get_algebraics_step_emt(self, x_t1:float, x_t2:float) -> float:
        x = np.array([x_t1, x_t2])
        y = self.C@x
        return y[0]
