import os
from dataclasses import dataclass, field
from typing import NamedTuple

import numpy as np
import plotly.graph_objects as go
import polars as pl

from sting.components import (
    ExcitationSystem4A,
    ParallelRCShunt2A,
    RotationalInertia2A,
    SeriesRLBranch2A,
    SpeedGovernor1A,
    SteamTurbine2A,
    SynchronousMachine7A,
    VoltageTransducer1A
)
from sting.generator.core import Generator
from sting.utils.dynamical_systems import DynamicalVariables, StateSpaceModel
from sting.utils.transformations import abc2dq0, dq02abc


class VariablesEMT(NamedTuple):
    x: DynamicalVariables
    u: DynamicalVariables
    y: DynamicalVariables


@dataclass(slots=True, kw_only=True, eq=False)
class SynchronousGenerator23A(Generator):
    """
    pass
    """
    # Shaft
    h_s: float
    kd_w_pu: float
    alpha: float = 0
    # Governor
    tau_g_s: float  # Time constant (in seconds)
    kr_pu: float    # Speed regulator gain (in pu)
    # Turbine
    tau_rh_s: float # Reheater time constant
    tau_ch_s: float # Inlet volumes time constant
    f_hp_pu: float  # Fraction of turbine power generated by the high pressure
    # Machine circuits (in standard parameterization)
    x_d_pu: float 
    x_q_pu: float 
    x_td_pu: float
    x_tq_pu: float
    x_std_pu: float
    x_stq_pu: float
    t_td0_s: float
    t_tq0_s: float
    t_std0_s: float
    t_stq0_s: float
    x_l_pu: float
    r_a_pu: float
    x_0_pu: float
    # Transducer + exciter
    tau_v_s: float # Voltage filter time constant
    tb_s: float    # Lead lag compensator
    tc_s: float
    ka_pu: float   # Amplifier
    ta_s: float
    te_s: float    # Exciter
    ke_pu: float
    tf_s: float    # Feedback stabilizer
    kf_pu: float
    # RC shunt
    rsh_pu: float
    csh_pu: float
    # Transformer and branch to grid
    txr_power_MVA: float
    txr_voltage1_kV: float
    txr_voltage2_kV: float
    txr_r1_pu: float
    txr_x1_pu: float
    txr_r2_pu: float
    txr_x2_pu: float

    # Components
    shaft: RotationalInertia2A = field(init=False)
    governor: SpeedGovernor1A = field(init=False)
    turbine: SteamTurbine2A = field(init=False)
    machine: SynchronousMachine7A = field(init=False)
    transducer: VoltageTransducer1A = field(init=False)
    exciter: ExcitationSystem4A = field(init=False)
    rc_shunt: ParallelRCShunt2A = field(init=False)
    rl_branch: SeriesRLBranch2A = field(init=False)


    @property
    def rbr_pu(self):
        return (self.txr_r1_pu + self.txr_r2_pu) * self.base_power_MVA / self.txr_power_MVA

    @property
    def xbr_pu(self):
        return (self.txr_x1_pu + self.txr_x2_pu) * self.base_power_MVA / self.txr_power_MVA
    
    @property
    def wbase(self):
        return 2 * np.pi * self.base_frequency_Hz

    def __post_init__(self):
        self.shaft = RotationalInertia2A(h_s=self.h_s, kd_w_pu=self.kd_w_pu, w_nom=self.wbase, alpha=self.alpha)
        self.governor = SpeedGovernor1A(tau_s=self.tau_g_s, kr_pu=self.kr_pu)
        self.turbine = SteamTurbine2A(tau_rh_s=self.tau_rh_s, tau_ch_s=self.tau_ch_s, f_hp_pu=self.f_hp_pu)
        self.machine = SynchronousMachine7A(
            x_d_pu=self.x_d_pu, x_q_pu=self.x_q_pu, x_l_pu=self.x_l_pu, r_a_pu=self.r_a_pu, 
            x_td_pu=self.x_td_pu, x_tq_pu=self.x_tq_pu, x_std_pu=self.x_std_pu, x_stq_pu=self.x_stq_pu,
            t_td0_s=self.t_td0_s, t_tq0_s=self.t_tq0_s, t_std0_s=self.t_std0_s, t_stq0_s=self.t_stq0_s,
            x_0_pu=self.x_0_pu, w_base=self.wbase
        )
        self.transducer = VoltageTransducer1A(tau_s=self.tau_v_s)
        self.exciter = ExcitationSystem4A(
            tb_s=self.tb_s, tc_s=self.tc_s, ka_pu=self.ka_pu, ta_s=self.ta_s, 
            te_s=self.te_s, ke_pu=self.ke_pu, tf_s=self.tf_s, kf_pu=self.kf_pu)
        self.rc_shunt = ParallelRCShunt2A(g_pu=1/self.rsh_pu, b_pu=self.csh_pu, wbase=self.wbase)
        self.rl_branch = SeriesRLBranch2A(r_pu=self.rbr_pu, x_pu=self.xbr_pu, wbase=self.wbase)

    def _calculate_emt_initial_conditions(self):
        # Unpack AC OPF solution
        v_bus_mag = self.power_flow_variables.vmag_bus
        relative_phase_deg = self.power_flow_variables.vphase_bus
        p_bus = self.power_flow_variables.p_bus
        q_bus = self.power_flow_variables.q_bus

        # Voltage in the end of the LCL filter
        phase_rad = relative_phase_deg * np.pi / 180
        v_bus_DQ = v_bus_mag * np.exp(phase_rad * 1j)
        # Current sent from the grid
        i_bus_DQ = (p_bus - q_bus * 1j) / np.conjugate(v_bus_DQ)
        # Voltage across the shunt element
        v_sh_DQ = v_bus_DQ + (self.rbr_pu + self.xbr_pu * 1j) * i_bus_DQ
        # Current flowing through shunt element
        i_sh_DQ = v_sh_DQ * (self.csh_pu * 1j) + v_sh_DQ / self.rsh_pu
        # Current sent from the synchronous machine
        i_sm_DQ = i_bus_DQ + i_sh_DQ

        v_ref_mag = np.abs(v_sh_DQ)
        p_ref = (i_sm_DQ*np.conj(v_sh_DQ)).real
        q_ref = -(i_sm_DQ*np.conj(v_sh_DQ)).imag

        # Compute all initial conditions
        self.rl_branch.get_steady_state(
            v_from_D=v_bus_DQ.real, v_from_Q=v_bus_DQ.imag,
            v_to_D=v_sh_DQ.real, v_to_Q=v_sh_DQ.imag,
            i_D=i_bus_DQ.real, i_Q=i_bus_DQ.imag,
        )
        self.rc_shunt.get_steady_state(
            i_D=i_sh_DQ.real, i_Q=i_sh_DQ.imag,
            v_D=v_sh_DQ.real, v_Q=v_sh_DQ.imag,
        )
        sm_init = self.machine.get_steady_state(
            v_angle_deg = np.angle(v_sh_DQ, deg=True), 
            v_mag = v_ref_mag,
            p = p_ref,
            q = q_ref,
        )
        t_e = self.machine.electrical_torque(
            i_d=sm_init.i_d, i_fd=sm_init.i_fd, i_1d=sm_init.i_1d,
            i_q=sm_init.i_q, i_1q=sm_init.i_1q, i_2q=sm_init.i_2q)
        # Initial per unit mechanical torque by balancing torques
        t_m = p_ref + t_e

        self.transducer.get_steady_state(v_d=v_sh_DQ.real, v_q=v_sh_DQ.imag)
        self.exciter.get_steady_state(v_ref=v_ref_mag, v_c=v_ref_mag, v_s=0)
        # Governor states are the change relative to nominal
        gov_init = self.governor.get_steady_state(p_ref=0, w=0)
        self.turbine.get_steady_state(v_cv=gov_init.x_gov, t_m=t_m)
        self.shaft.get_steady_state(p_ref=p_ref, angle=self.machine.emt_init.angle, w=1)


    def _build_small_signal_model(self):
        pass

    def _build_quadratic_bilinear_model(self):
        pass

    def define_variables_emt(self):
        states = [
            # Rotational inertia of the shaft
            ("angle", self.shaft.emt_init.angle),
            ("w", self.shaft.emt_init.w),
            # Governor
            ("governor", self.governor.emt_init.x_gov),
            # Turbine
            ("turbine_x1", self.turbine.emt_init.x_t1),
            ("turbine_x2", self.turbine.emt_init.x_t2),
            # Synchronous machine
            ("i_stator_d", self.machine.emt_init.i_d),
            ("i_stator_q", self.machine.emt_init.i_q),
            ("i_stator_0", self.machine.emt_init.i_0),
            ("i_field_d", self.machine.emt_init.i_fd),
            ("i_damper_1d", self.machine.emt_init.i_1d),  
            ("i_damper_1q", self.machine.emt_init.i_1q),  
            ("i_damper_2q", self.machine.emt_init.i_2q),  
            # Transducer + exciter
            ("transducer_vmag", self.transducer.emt_init.v_c1),
            ("exciter_leadlag", self.exciter.emt_init.x_l),
            ("exciter_amplifier", self.exciter.emt_init.x_a),
            ("exciter_exciter", self.exciter.emt_init.x_e),
            ("exciter_damper", self.exciter.emt_init.x_f),
            # RC shunt
            ("v_shunt_a", self.rc_shunt.emt_init.v_a),
            ("v_shunt_b", self.rc_shunt.emt_init.v_b),
            ("v_shunt_c", self.rc_shunt.emt_init.v_c),
            # RL branch
            ("i_bus_a", self.rl_branch.emt_init.i_a),
            ("i_bus_b", self.rl_branch.emt_init.i_b),
            ("i_bus_c", self.rl_branch.emt_init.i_c),
        ]
        # States 
        name, init = map(list, zip(*states))
        x = DynamicalVariables(name=name, init=init, component=f"{self.type_}_{self.id}")


        init = self.rl_branch.emt_init

        # Inputs 
        u = DynamicalVariables(
            name=["p_ref", "v_ref", "v_bus_a", "v_bus_b", "v_bus_c"],
            component=f"{self.type_}_{self.id}",
            type=["device", "device", "grid", "grid", "grid"],
            init=[
                self.shaft.emt_init.p_ref, 
                self.exciter.emt_init.v_ref, 
                init.v_to_a, init.v_to_b, init.v_to_c]
        )

        # Outputs
        y = DynamicalVariables(
            name=["i_bus_a", "i_bus_b", "i_bus_c"],
            component=f"{self.type_}_{self.id}",
            init=[init.i_a, init.i_b, init.i_c]
        )
        
        self.variables_emt = VariablesEMT(x=x,u=u,y=y)
    
    def get_derivative_state_emt(self, x: np.ndarray, u: np.ndarray) -> np.ndarray:
        # Unpacking states and inputs
        angle, w, \
        x_gov, x_t1, x_t2, \
        i_d, i_q, i_0, i_fd, i_1d, i_1q, i_2q, \
        v_c, x_l, x_a, x_e, x_f, \
        v_sh_a, v_sh_b, v_sh_c, \
        i_bus_a, i_bus_b, i_bus_c = x

        p_ref, v_ref, v_bus_a, v_bus_b, v_bus_c = u

        # -------------------- #
        # Algebraic operations #
        # -------------------- #
        # The speed-governor state *is* the change in the turbine control valve
        v_cv = x_gov
        delta_p_ref = p_ref - self.shaft.emt_init.p_ref
        delta_w = w - 1
        # Compute the exciter output field voltage by adding the initial field voltage back
        v_fd = x_e + self.machine.emt_init.v_fd
        # Shunt voltage abc to dq0
        v_sh_d, v_sh_q, v_sh_0 = abc2dq0(v_sh_a, v_sh_b, v_sh_c, angle)
        # Synchronous machine dq0 to abc
        i_sm_a, i_sm_b, i_sm_c = dq02abc(i_d, i_q, i_0, angle)
        # Flow of current into the shunt by KCL
        i_sh_a = i_sm_a - i_bus_a
        i_sh_b = i_sm_b - i_bus_b
        i_sh_c = i_sm_c - i_bus_c
        # Change in mechanical torque on the turbine
        delta_t_m = self.turbine.get_algebraics_step_emt(x_t1=x_t1, x_t2=x_t2)
        # Add back initial conditions to get absolute torque
        t_m = self.turbine.emt_init.t_m + delta_t_m
        # Air gap torque
        t_e = self.machine.electrical_torque( 
            i_d=i_d, i_q=i_q, i_fd=i_fd, i_1d=i_1d, i_1q=i_1q, i_2q=i_2q)
        # Net accelerating torque on the shaft
        p = t_m - t_e
        # ----------------------- #
        # Differential operations #
        # ----------------------- #
        dx = []
        dx += self.shaft.get_derivatives_step_emt_abc(w=w, p_ref=p_ref, p=p)
        dx += self.governor.get_derivatives_step_emt(x_gov=x_gov, p_ref=delta_p_ref, w=delta_w)
        dx += self.turbine.get_derivatives_step_emt(x_t1=x_t1, x_t2=x_t2, v_cv=v_cv)
        dx += self.machine.get_derivatives_step_emt_dq0(
            i_d=i_d, i_q=i_q, i_0=i_0, i_fd=i_fd, i_1d=i_1d, i_1q=i_1q, i_2q=i_2q,
            v_d=v_sh_d, v_q=v_sh_q, v_0=v_sh_0, v_fd=v_fd, w=w
            )
        dx += self.transducer.get_derivatives_step_emt_dq0(v_c1=v_c, v_d=v_sh_d, v_q=v_sh_q)
        dx += self.exciter.get_derivatives_step_emt_dq0(
            x_l=x_l, x_a=x_a, x_e=x_e, x_f=x_f, 
            v_ref=v_ref, v_c=v_c, v_s=0
            )
        dx += self.rc_shunt.get_derivatives_step_emt_abc(
            v_sh_a=v_sh_a, v_sh_b=v_sh_b, v_sh_c=v_sh_c, 
            i_sh_a=i_sh_a, i_sh_b=i_sh_b, i_sh_c=i_sh_c
            )
        dx += self.rl_branch.get_derivatives_step_emt_abc(
            i_a=i_bus_a, i_b=i_bus_b, i_c=i_bus_c,
            v_from_a=v_sh_a, v_from_b=v_sh_b, v_from_c=v_sh_c, 
            v_to_a=v_bus_a, v_to_b=v_bus_b, v_to_c=v_bus_c
            )

        return dx

    def get_output_emt(self, x: np.ndarray) -> np.ndarray:
        angle, w, \
        x_gov, x_t1, x_t2, \
        i_d, i_q, i_0, i_fd, i_1d, i_1q, i_2q, \
        v_c, x_l, x_a, x_e, x_f, \
        v_sh_a, v_sh_b, v_sh_c, \
        i_bus_a, i_bus_b, i_bus_c = x

        return [i_bus_a, i_bus_b, i_bus_c]
    
    def plot_results_emt(self):
        angle, w, \
        x_gov, x_t1, x_t2, \
        i_d, i_q, i_0, i_fd, i_1d, i_1q, i_2q, \
        v_c, x_l, x_a, x_e, x_f, \
        v_sh_a, v_sh_b, v_sh_c, \
        i_bus_a, i_bus_b, i_bus_c = self.variables_emt.x.value

        # Transform abc to dq0
        v_sh_d, v_sh_q, _ = zip(*[abc2dq0(a, b, c, ang) for a, b, c, ang in zip(v_sh_a, v_sh_b, v_sh_c, angle)])
        i_bus_d, i_bus_q, _ = zip(*[abc2dq0(a, b, c, ang) for a, b, c, ang in zip(i_bus_a, i_bus_b, i_bus_c, angle)])

        names = [
            "angle", "w", 
            "governor", "turbine_x1", "turbine_x2", 
            "i_stator_d", "i_stator_q", "i_stator_0", "i_field_d", "i_damper_1d", "i_damper_1q", "i_damper_2q", 
            "transducer_vmag","exciter_leadlag","exciter_amplifier","exciter_exciter","exciter_damper", 
            "v_sh_d", "v_sh_q", "i_bus_d", "i_bus_q"
        ]
        values = [
            angle, w,
            x_gov, x_t1, x_t2,
            i_d, i_q, i_0, i_fd, i_1d, i_1q, i_2q,
            v_c, x_l, x_a, x_e, x_f, 
            v_sh_d, v_sh_q, i_bus_d, i_bus_q 
            ]

        results = DynamicalVariables(
            name=names,
            component=f"{self.type_}_{self.id}",
            value=values,
            time=self.variables_emt.x.time
        )
        return results
